packages:
  - packages/*
  - apps/*

blockExoticSubdeps: true

catalog:
  '@tailwindcss/postcss': 4.2.4
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 6.0.1
  postcss: 8.5.10
  react: 19.2.5
  react-dom: 19.2.5
  tailwindcss: 4.2.4
  vite-plus: 0.1.19

allowBuilds:
  esbuild: false
  sharp: false

verifyDepsBeforeRun: install

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@k8o/*'
