// AUTO-GENERATED by scripts/generate-catalog.ts. Do not edit by hand.
// Source: @k8o/arte-odyssey@7.0.1

import type {
  ComponentRegistry,
  ComponentRenderProps,
} from '@json-render/react';
import {
  Accordion,
  Anchor,
  Autocomplete,
  Avatar,
  Badge,
  BaselineStatus,
  Checkbox,
  CheckboxCard,
  CheckboxGroup,
  Code,
  Form,
  Heading,
  IconButton,
  IconLink,
  InteractiveCard,
  LinkButton,
  NumberField,
  PasswordInput,
  Progress,
  Radio,
  RadioCard,
  ScrollLinked,
  Select,
  Separator,
  Skeleton,
  Slider,
  Spinner,
  Switch,
  TextField,
  Textarea,
} from '@k8o/arte-odyssey';
import { type ComponentType, createElement } from 'react';

const passthrough = (
  Component: ComponentType<Record<string, unknown>>,
  displayName: string,
) => {
  const renderer = ({ element, children }: ComponentRenderProps) =>
    createElement(Component, element.props, children);
  renderer.displayName = displayName.concat('Renderer');
  return renderer;
};

export const generatedRegistry: ComponentRegistry = {
  Accordion: passthrough(
    Accordion as unknown as ComponentType<Record<string, unknown>>,
    'Accordion',
  ),
  Anchor: passthrough(
    Anchor as unknown as ComponentType<Record<string, unknown>>,
    'Anchor',
  ),
  Autocomplete: passthrough(
    Autocomplete as unknown as ComponentType<Record<string, unknown>>,
    'Autocomplete',
  ),
  Avatar: passthrough(
    Avatar as unknown as ComponentType<Record<string, unknown>>,
    'Avatar',
  ),
  Badge: passthrough(
    Badge as unknown as ComponentType<Record<string, unknown>>,
    'Badge',
  ),
  BaselineStatus: passthrough(
    BaselineStatus as unknown as ComponentType<Record<string, unknown>>,
    'BaselineStatus',
  ),
  Checkbox: passthrough(
    Checkbox as unknown as ComponentType<Record<string, unknown>>,
    'Checkbox',
  ),
  CheckboxCard: passthrough(
    CheckboxCard as unknown as ComponentType<Record<string, unknown>>,
    'CheckboxCard',
  ),
  CheckboxGroup: passthrough(
    CheckboxGroup as unknown as ComponentType<Record<string, unknown>>,
    'CheckboxGroup',
  ),
  Code: passthrough(
    Code as unknown as ComponentType<Record<string, unknown>>,
    'Code',
  ),
  Form: passthrough(
    Form as unknown as ComponentType<Record<string, unknown>>,
    'Form',
  ),
  Heading: passthrough(
    Heading as unknown as ComponentType<Record<string, unknown>>,
    'Heading',
  ),
  IconButton: passthrough(
    IconButton as unknown as ComponentType<Record<string, unknown>>,
    'IconButton',
  ),
  IconLink: passthrough(
    IconLink as unknown as ComponentType<Record<string, unknown>>,
    'IconLink',
  ),
  InteractiveCard: passthrough(
    InteractiveCard as unknown as ComponentType<Record<string, unknown>>,
    'InteractiveCard',
  ),
  LinkButton: passthrough(
    LinkButton as unknown as ComponentType<Record<string, unknown>>,
    'LinkButton',
  ),
  NumberField: passthrough(
    NumberField as unknown as ComponentType<Record<string, unknown>>,
    'NumberField',
  ),
  PasswordInput: passthrough(
    PasswordInput as unknown as ComponentType<Record<string, unknown>>,
    'PasswordInput',
  ),
  Progress: passthrough(
    Progress as unknown as ComponentType<Record<string, unknown>>,
    'Progress',
  ),
  Radio: passthrough(
    Radio as unknown as ComponentType<Record<string, unknown>>,
    'Radio',
  ),
  RadioCard: passthrough(
    RadioCard as unknown as ComponentType<Record<string, unknown>>,
    'RadioCard',
  ),
  ScrollLinked: passthrough(
    ScrollLinked as unknown as ComponentType<Record<string, unknown>>,
    'ScrollLinked',
  ),
  Select: passthrough(
    Select as unknown as ComponentType<Record<string, unknown>>,
    'Select',
  ),
  Separator: passthrough(
    Separator as unknown as ComponentType<Record<string, unknown>>,
    'Separator',
  ),
  Skeleton: passthrough(
    Skeleton as unknown as ComponentType<Record<string, unknown>>,
    'Skeleton',
  ),
  Slider: passthrough(
    Slider as unknown as ComponentType<Record<string, unknown>>,
    'Slider',
  ),
  Spinner: passthrough(
    Spinner as unknown as ComponentType<Record<string, unknown>>,
    'Spinner',
  ),
  Switch: passthrough(
    Switch as unknown as ComponentType<Record<string, unknown>>,
    'Switch',
  ),
  TextField: passthrough(
    TextField as unknown as ComponentType<Record<string, unknown>>,
    'TextField',
  ),
  Textarea: passthrough(
    Textarea as unknown as ComponentType<Record<string, unknown>>,
    'Textarea',
  ),
};
